spring.application.name=employee
server.port=8081

spring.jackson.deserialization.fail-on-null-for-primitives=false


spring.datasource.url=JDBC:mysql://localhost:3306/employee
spring.datasource.username=root
spring.datasource.password=@Bhuvan18
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/employee-realm